config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :members do
      get :export, on: :collection
    end
    resources :payments

    root to: 'users#index'
  end

  resources :members
  devise_for :users
  root to: 'home#index'
  get '/privacy-policy', to: 'home#privacy_policy'

  post '/create-paypal-transaction', as: :paypal_transaction, to: 'paypal#create'

  post '/api/member_status', to: 'api/members#status'
end

app/views/layouts/_development_banner.html.erb
<% if Rails.env.development? %>
  <div class="alert alert-warning" role="alert">
    <b>Development Environment</b>
    All email is intercepted in this environment. To view email
    <%= link_to "Click here", "http://localhost:1080", target: :_blank %>
  </div>
<% end %>

app/views/layouts/_flashes.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger" role="alert"><%= alert %></div>
<% end %>

app/views/layouts/_footer.html.erb
<% # from https://getbootstrap.com/docs/4.0/examples/sticky-footer-navbar/
%>

<footer class="footer mt-auto py-3">
  <div class="container">
    <%= link_to "Privacy Policy", privacy_policy_path, class: "text-muted" %>
  </div>
</footer>

app/views/layouts/_nav_bar.html.erb
<header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <%= link_to "IUF Membership", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Members", members_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
        <!-- <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li> -->
        <!-- <li class="nav-item">
          <a class="nav-link disabled" href="#">Disabled</a>
        </li> -->
      </ul>
      <% if user_signed_in? %>
        <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "navbar-text" %>
      <% end %>
      <!-- <form class="form-inline mt-2 mt-md-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form> -->
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-100">
  <head>
    <title>IUF Membership management</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://cdnjs.cloudflare.com/polyfill/v2/polyfill.min.js"></script>
    <script src="https://www.paypal.com/sdk/js?client-id=<%= Rails.configuration.paypal_client_id %>&currency=<%= Rails.configuration.currency %>">
</script>
  </head>

  <body class="d-flex flex-column h-100">
    <%= render "layouts/nav_bar" %>

    <main role="main" class="flex-shrink-0">
      <div class="container">
        <%= render "layouts/development_banner" %>
        <%= render "layouts/flashes" %>
        <%= yield %>
      </div>
    </main>

    <%= render "layouts/footer" %>
  </body>
</html>