config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :members do
      get :export, on: :collection
    end
    resources :payments

    root to: 'users#index'
  end

  resources :members
  devise_for :users
  root to: 'home#index'
  get '/privacy-policy', to: 'home#privacy_policy'

  post '/create-paypal-transaction', as: :paypal_transaction, to: 'paypal#create'

  post '/api/member_status', to: 'api/members#status'
end

app/models/member.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: members
#
#  id                   :bigint           not null, primary key
#  alternate_first_name :string
#  alternate_last_name  :string
#  birthdate            :date
#  contact_email        :string
#  first_name           :string
#  last_name            :string
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  iuf_id               :integer
#  user_id              :bigint           not null
#
# Indexes
#
#  index_members_on_iuf_id   (iuf_id) UNIQUE
#  index_members_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Member < ApplicationRecord
  belongs_to :user
  has_many :payments, dependent: :restrict_with_error

  validates :first_name, :last_name, :birthdate, presence: true
  validate :must_be_unique_if_paid_exists

  def to_s
    [first_name, last_name].join(' ')
  end

  def active?(as_of_date = DateTime.current)
    payments.any? do |payment|
      payment.active?(as_of_date)
    end
  end

  def recent_purchase?
    payments.select(&:recent?)
  end

  def first_name=(name)
    super(name&.strip)
  end

  def last_name=(name)
    super(name&.strip)
  end

  def expiration_date
    payments.select(&:active?).map(&:expiration_date).max
  end

  private

  def must_be_unique_if_paid_exists
    # return unless first_name.present?
    # return unless last_name.present?
    return if birthdate.blank?

    matching_members = MemberFinder.find_all(
      first_name: first_name,
      last_name: last_name,
      birthdate: birthdate.to_s
    ).reject { |member| member.id == id }

    errors.add(:base, 'A paid membership already exists for this name/birthday combination') if matching_members.any?(&:active?)
  end
end

app/controllers/admin/members_controller.rb
# frozen_string_literal: true

module Admin
  # Admin view and export pages for Members (and the associated User email)
  class MembersController < Admin::ApplicationController
    include AdministrateExportable::Exporter
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/api/members_controller.rb
# frozen_string_literal: true

module Api
  # Handle queries from 3rd party system about membership in the IUF
  class MembersController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :skip_authorization

    def status
      member = MemberFinder.find_paid(
        first_name: params[:first_name],
        last_name: params[:last_name],
        birthdate: params[:birthdate],
        eventdate: params[:eventdate]
      )

      if member
        render json: { member: true, iuf_member_id: format('IUF%<member_id>05d', member_id: member.iuf_id) }
      else
        render json: { member: false }
      end
    end

    private

    def find_member(params)
      bday = Date.parse(params[:birthdate])

      Member.find_by(
        first_name: params[:first_name],
        last_name: params[:last_name],
        birthdate: bday
      )
    end
  end
end

app/controllers/members_controller.rb
# frozen_string_literal: true

# Manage the creation/payment of a member
class MembersController < ApplicationController
  before_action :authenticate_user!

  def index
    authorize(Member)
    @members = current_user.members
    redirect_to new_member_path if @members.none?
  end

  def new
    @member = Member.new
    authorize(@member)
  end

  def create
    @member = Member.new(member_params)
    authorize(@member)
    @member.user = current_user

    if @member.save
      redirect_to member_path(@member), notice: 'Member created'
    else
      flash.now[:alert] = 'Unable to save member'
      render :new
    end
  end

  def show
    @member = Member.find(params[:id])
    authorize(@member)

    @recent_membership_purchase = @member.recent_purchase? && @member
  end

  def edit
    @member = Member.find(params[:id])
    authorize(@member)
  end

  def update
    @member = Member.find(params[:id])
    authorize(@member)

    if @member.update(member_params)
      redirect_to member_path(@member), notice: 'Member updated'
    else
      flash.now[:alert] = 'Unable to save member'
      render :edit
    end
  end

  def destroy
    @member = Member.find(params[:id])
    if @member.destroy
      redirect_to members_path, notice: 'Member deleted'
    else
      redirect_to members_path, alert: 'Unable to delete member'
    end
  end

  private

  def member_params
    params.require(:member).permit(
      :first_name,
      :alternate_first_name,
      :last_name,
      :alternate_last_name,
      :birthdate,
      :contact_email
    )
  end
end

app/views/members/_form.html.erb
<%= form_with(model: member, local: true) do |f| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(member.errors.count, "error") %> prohibited
        this member from being saved:
      </h2>
      <ul>
        <% member.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :birthdate %>
    <%= f.date_field :birthdate %>
  </p>
  <div>
    <b>Note: </b>Name and birthdate have to match this system and the registration site.
    <br>
    If you go by a different name
    <a href="#" class="js--altname">click here</a> to enter your other name. (which will also be checked when confirming IUF membership)
  </div>

  <div class="js--altname_target is--hidden">
    <p>
      <%= f.label :alternate_first_name %>
      <%= f.text_field :alternate_first_name %>
    </p>

    <p>
      <%= f.label :alternate_last_name %>
      <%= f.text_field :alternate_last_name %>
    </p>
  </div>

  <p>
    <%= f.label :contact_email %>
    <%= f.email_field :contact_email %>
  </p>

  <p>
    <%= f.submit class: "btn btn-primary" %>
  </p>
<% end %>

app/views/members/_payment_form.html.erb
<script src="https://www.paypal.com/sdk/js?client-id=<%= Rails.configuration.paypal_client_id %>&currency=<%= Rails.configuration.currency %>"></script>

<div id="paypal-button-container" style="text-align: center"></div>

<script>
  paypal.Buttons({
    createOrder: function(data, actions) {
      return actions.order.create({
        application_context: {
          shipping_preference: "NO_SHIPPING",
        },
        purchase_units: [{
          custom_id: "<%= @member.id %>",
          amount: {
            value: '<%= Rails.configuration.membership_cost %>'
          }
        }]
      });
    },
    onApprove: function(data, actions) {
      return fetch("<%= paypal_transaction_path %>", {
        method: 'post',
        headers: {
          'content-type': 'application/json'
        },
        body: JSON.stringify({
          orderID: data.orderID
        })
      }).then(function(res) {
        return res.json();
      }).then(function(details) {
        location.reload();
        return;
      });
    }
  }).render('#paypal-button-container');
</script>
<% if Rails.configuration.paypal_mode == 'test' %>
  <div class="alert alert-info">
    <b>Paypal TEST server</b>: You can use paypal fake creditcard numbers like '4242 4242 4242 4242' to "pay" in the TEST system.
  </div>
<% end %>

app/views/members/edit.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Edit Member</h1>
    <%= render "form", member: @member %>
  </div>
</div>

app/views/members/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>My Members</h1>

    <p>
      <b>Note:</b> If you are registering more than 1 member, you are responsible for ensuring that each member receives any e-mail/contact-info passed to you for them from the IUF.
    </p>
    <p>
      Members:
      <ul>
        <% @members.each do |member| %>
          <li><%= link_to member.to_s, member_path(member) %></li>
        <% end %>
      </ul>
    </p>
    <p><%= link_to "New membership", new_member_path, class: "btn btn-primary btn-lg" %></p>
  </div>
</div>

app/views/members/new.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>New Member</h1>
    <%= render "form", member: @member %>
  </div>
</div>

app/views/members/show.html.erb
<% if @recent_membership_purchase %>
  <div class="alert alert-success" role="alert">
    Your IUF registration is now finished. If you were in the process of registering to a unicycle convention (Unicon or another one), please, go back to your convention registration and click the "Recheck IUF Status" button.
  </div>
<% end %>

<div class="jumbotron">
  <div class="container">
    <h1>Member</h1>
    <ul>
      <li><b>First Name: </b><%= @member.first_name %></li>
      <li><b>Last Name: </b><%= @member.last_name %></li>
      <li><b>Birthdate: </b><%= @member.birthdate.to_fs(:long) %></li>
      <li><b>Contact Email: </b><%= @member.contact_email %></li>
    </ul>
    <% if policy(@member).edit? %>
      <%= link_to "Edit", edit_member_path(@member), class: "btn btn-primary btn-large" %>
    <% end %>
  </div>
</div>

<% if @member.active? %>
  <div class="alert alert-info">
    <b>Active IUF Member</b>
    <br>
    Your membership expires <%= @member.expiration_date.to_date %>
    <br>
    <b>Note:</b> If you've been sent here but your membership is currently active, this is probably because your membership will expire before the end of the upcoming UNICON. Please purchase a new membership to continue.
    <br>
    Using Paypal below, pay for your membership now.
  </div>
<% else %>
  <div class="alert alert-danger">
    <b>Unpaid Member</b>
    Using Paypal below, pay for your membership now.
    <br>
    The price of IUF membership is <%= Rails.configuration.membership_cost %> <%= Rails.configuration.currency %>
  </div>
<% end %>

<div class="container">
  <%= render "payment_form", member: @member %>
</div>

<hr>
<% if @member.payments.any? %>
  <h2>Payments:</h2>
  <ul>
    <% @member.payments.each do |payment| %>
      <li>Invoice Number <%= payment.id %> (received: <%= payment.created_at.to_date %>, start_date: <%= payment.start_date.to_date %>, expires_at: <%= payment.expiration_date.to_date %></li>
    <% end %>
  </ul>
<% end %>